

import { Geist, Geist_Mono } from "next/font/google";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import { Suspense } from "react"
// import { ConvexClientProvider } from "./ConvexClientProvider";
import Provider  from "./Provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StackProvider app={stackServerApp}><StackTheme>
        {/* <Suspense fallback={<div>Loading...</div>}> */}
        <Provider>
          {children}
        </Provider>
         {/* </Suspense> */}
      </StackTheme>
      </StackProvider>
      </body>
    </html>
  );
}


// app/(main)/layout.js
// "use client"

// import { Suspense } from "react"
// import { StackProvider, StackTheme } from "@stackframe/stack"
// import { stackServerApp } from "../../stack"
// import Provider from "../Provider"

// export default function MainLayout({ children }) {
//   return (
//     <StackProvider app={stackServerApp}>
//       <StackTheme>
//         <Suspense fallback={<div>Loading app...</div>}>
//           <Provider>{children}</Provider>
//         </Suspense>
//       </StackTheme>
//     </StackProvider>
//   )
// }
